# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: registry.gitlab.com/stage-right-labs/lims-api

# Select what we should cache between builds
cache:
  paths:
  - vendor/

before_script:
# Install and run Composer
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install --prefer-source --no-interaction --no-suggest
# Set the default application environment variables
- cp .env.example .env
- php artisan key:generate
# Run the migrations
- php artisan migrate
# Configure the OAuth service
- php artisan passport:install

services:
  - postgres:latest

# Establish the necessary system environment variables
variables:
  POSTGRES_DB: lims-testing
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: "secret"
  APP_ENV: testing
  DB_CONNECTION: pgsql
  DB_HOST: postgres
  DB_PORT: 5432
  DB_DATABASE: lims-testing
  DB_USERNAME: runner
  DB_PASSWORD: secret

# Run our tests
unit_tests:
  script:
  - vendor/bin/phpunit --configuration phpunit.xml --colors=never
