# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: php:7.2

# Select what we should cache between builds
cache:
  paths:
  - vendor/

before_script:
- apt-get update -yqq
- apt-get install -yqq git unzip libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev
# Install PHP extensions
- docker-php-ext-install mbstring pdo_pgsql curl json intl gd xml zip bz2 opcache
# Install and run Composer
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install

# Bring in any services we need http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# See http://docs.gitlab.com/ce/ci/services/README.html for examples.
services:
  - postgres:latest

# Set any variables we need
variables:
  POSTGRES_DB: lims-testing
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: "secret"
  DB_HOST: postgres
  DB_PORT: 5432
  DB_DATABASE: lims-testing
  DB_USERNAME: runner
  DB_PASSWORD: secret

# Run our tests
test:
  script:
  - php artisan passport:install
  - vendor/bin/phpunit --configuration phpunit.xml --colors=never
